CREATE TABLE IF NOT EXISTS cliente_contactos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cliente_id INTEGER NOT NULL,
    tipo_contacto TEXT NOT NULL,
    parentesco TEXT,
    cliente_referenciado_id INTEGER,
    nombre TEXT,
    primer_apellido TEXT,
    segundo_apellido TEXT,
    nie TEXT,
    pasaporte TEXT,
    dni TEXT,
    nacionalidad TEXT,
    fecha_nacimiento TEXT,
    telefono TEXT,
    email TEXT,
    estado_cliente TEXT,
    domicilio_espana TEXT,
    localidad TEXT,
    provincia TEXT,
    codigo_postal TEXT,
    localidad_nacimiento TEXT,
    pais_nacimiento TEXT,
    nombre_padre TEXT,
    nombre_madre TEXT,
    estado_civil TEXT,
    sexo TEXT,
    observaciones TEXT,
    observaciones_internas TEXT,
    activo INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
    FOREIGN KEY (cliente_referenciado_id) REFERENCES clientes(id)
);
